owner: asar-studio
repo: upptime
user-agent: asar-studio

sites:
  - name: РУСДРАМ
    url: https://rusdram.org/
  - name: Leon Hotel
    url: https://leonhotel.net/
  - name: VISIT-ABKHAZIA
    url: https://visit-abkhazia.ru/

status-website:
  cname: github-uptime.asar.studio
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/asar-studio/uptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/asar-studio/uptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/asar-studio/uptime
